export enum ROUTE_NAMES {
  LOGIN = 'LOGIN',
  APP_CONTENT = 'APP_CONTENT',
  FEED = 'FEED',
  WATCH = 'WATCH',
  PROFILE = 'PROFILE',
  PROFILE_USER = 'PROFILE_USER',
  UPLOAD = 'UPLOAD',
  ADMIN_PANEL = 'ADMIN_PANEL',
}
